### ISSUE TITLE
Add an option that replaces units and structures in task forces and triggers with profiles.

### ISSUE THREAD

**Issue by MikillRosen** [Starkku/MapTool#1]
Here's an example: I used a profile which replaces Unit A with Unit B and Structure A with Structure B but it didn't touch task forces and triggers which is bad in this case. This is where this option I'm suggesting comes in. You click on it to check it, start replacing using said profile and now Unit A is replaced with Unit B in task forces that had Unit A and Structure A is replaced with Structure B in triggers that had something to do with Structure A (I just realized that triggers use a BuildingType's index, not a BuildingType's internal name so maybe it's not possible to replace structures in triggers.)

**Comment by Starkku** [comment]
Trigger/tag/action/event manipulation is currently out of the scope of the tool and the feature requested, as you already realized, cannot be implemented in the way asked. Will re-open and re-address if trigger manipulation ever gets included.
