### ISSUE TITLE
Add a new feature to replace upgraded structures with non-upgraded structures.

### ISSUE THREAD

**Issue by MikillRosen** [Starkku/MapTool#2]
Here's an example:
[ObjectRules]
GACTWR+GAVULC|GAPILL

This tells MapTool to replace Component Towers that have the Vulcan Cannon upgrade with Pillboxes.

**Comment by Starkku** [comment]
Added in 39f3be676b8f4841f15879bb3c59be85676b8c49.

Works in similar way to the proposed example, only more flexible & powerful. ObjectRules section of [documentation](https://github.com/Starkku/MapTool/blob/39f3be676b8f4841f15879bb3c59be85676b8c49/Conversion-Profile-Documentation.md) contains examples.
